<<<<<<< HEAD
import Logo from '../Components/Logo/index'
import Gallery from '../Components/Gallery/index'
import Map from '../Components/Map/index'
import MyMap from '../Components/Map/index'


export default function Home() {
  return (
    <div>
   <Logo />
   <Gallery />
=======
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import SearchBar from "../Components/SearchBar/SearchBar.js";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchBar />
>>>>>>> bc11b294a8d29b51f3d0bd7bcea250c9c85ac5fd
    </div>
  );
}
